name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - plotly
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - ipywidgets
